### PR TITLE
Allow configuration of velocityIterations and positionIterations

### PR DESCRIPTION
**Pull request by dynamicbutter**
For my use case I can get by with values of 2 and 1, and lowering these allows me to have more bodies before exceeding the 60 fps frame rate.

### CODE REVIEW

**Comment by spydon** [comment]
Hi, we don't want to have more optional arguments unfortunately.
But this is easy for you to solve anyways, just extend `Forge2DGame` and override those fields.

**Comment by dynamicbutter** [comment]
Yeah, I get it, optional arguments are ugly.  Since they are declared final I can't do it in the constructor (which is what I had thought to do).  But as you pointed out, I could override the `update` method and pass my own values to `stepDt`.

**Comment by spydon** [comment]
You don't have to override the update method, you can just do like this:
```dart
class MyGame extends Forge2DGame {
  @override
  final int velocityIterations = 2;
  @override
  final int positionIterations = 2;

  ...
}
```

**Comment by dynamicbutter** [comment]
👍

**Pull request closed without merging**
