### PR TITLE
Add sprite animation body component

### PR DESCRIPTION
**Pull request by Alex-A4**
Hi!
I wrote SpriteAnimationBodyComponent to allow developers create body component with animation out of the box.
Also added doc for component and example.

### CODE REVIEW

**Comment by spydon** [comment]
Nice work! Will review it a bit later today. Can you add a line to the changelog describing your change?

**Comment by Alex-A4** [comment]
Should I add this to current [next] section or create other one?

**Comment by spydon** [comment]
> Should I add this to current [next] section or create other one?

The current one

**Comment by spydon** [comment]
Instead of re-implementing the methods that are on the `SpriteAnimationComponent`, can you follow the same pattern as on `SpriteBodyComponent` where it simply is a normal flame component on top of the `BodyComponent`? It will be a lot easier to maintain.

Or maybe, another better idea might be to make this solution even more general, with a `BodyComponent` that can have any type of `PositionComponent` on top of it, what do you think?

**Comment by Alex-A4** [comment]
The idea of this component is to allow users to display static sprite or animated one. So I've combine SpriteAnimatedComponent with SpriteComponent in one BodyComponent

**Comment by Alex-A4** [comment]
Other idea: rename this component to SpriteCombinedAnimatedBodyComponent and create its own SpriteAnimationBodyComponent without abstraction

**Comment by spydon** [comment]
> The idea of this component is to allow users to display static sprite or animated one. So I've combine SpriteAnimatedComponent with SpriteComponent in one BodyComponent

It is a good idea, but I think it should be done in the main flame repository, and then that component can be shown on top of a body.

**Comment by drachim-dev** [comment]
Any update on this?

**Comment by spydon** [comment]
@drachim-dev yes, we have decided that this will be closed in favor of putting an arbitrary `PositionComponent` on top of a `BodyComponent` instead, the graphical part of things belong more in Flame than Forge2D.

I'll hopefully get some time this weekend to write up a PR for that.

**Comment by spydon** [comment]
But thanks for your contribution anyways @Alex-A4, it sparked some design discussions for sure!

**Pull request closed without merging**
